Repository boostcampwm-2021/iOS10-JipJung, pull requests merged in 2021-11, with the labels that each got.

#6 프로젝트 설정하기
  .gitattributes
  .github/COMMIT_TEMPLATE/message.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: 🔧conf

#9 프로젝트 설정하기
  JipJung/.swiftlint.yml
  JipJung/JipJung.xcworkspace/contents.xcworkspacedata
  JipJung/JipJung.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  JipJung/JipJung/AppDelegate.swift
  JipJung/JipJung/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/Assets.xcassets/Contents.json
  JipJung/JipJung/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/Info.plist
  JipJung/JipJung/SceneDelegate.swift
  JipJung/JipJung/ViewController.swift
  JipJung/Podfile
  JipJung/Podfile.lock
Labels: 🔧conf

#12 🐛 gitignore.io 설정이슈로 인한 xcodeproj 누락
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  JipJung/JipJung.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Labels: 🐛 bug

#16 🚑️ app 폴더 보이지않는 이슈 해결하기
  JipJung/JipJung/App/AppDelegate.swift
  JipJung/JipJung/App/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/App/Assets.xcassets/Contents.json
  JipJung/JipJung/App/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/App/SceneDelegate.swift
Labels: 🐛 bug

#20 🔧 프로젝트 폴더 구조 정의
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/AppDelegate.swift
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/Application/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/Contents.json
  JipJung/JipJung/Application/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/Assets.xcassets/Contents.json
  JipJung/JipJung/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/Data/Interfaces/File.swift
  JipJung/JipJung/Data/Repositories/File.swift
  JipJung/JipJung/Domain/Entities/File.swift
  JipJung/JipJung/Domain/Interfaces/File.swift
  JipJung/JipJung/Domain/UseCases/Protocol/File.swift
  JipJung/JipJung/Infra/File/File.swift
  JipJung/JipJung/Infra/LocalDB/File.swift
  JipJung/JipJung/Infra/Network/File.swift
  JipJung/JipJung/Infra/UserDefaults/File.swift
  JipJung/JipJung/SceneDelegate.swift
  JipJung/JipJung/UI/Common/Example.swift
  JipJung/JipJung/UI/Explore/Main/File.swift
  JipJung/JipJung/UI/Explore/Search/File.swift
  JipJung/JipJung/UI/Home/Categories/File.swift
  JipJung/JipJung/UI/Home/Focus/File.swift
  JipJung/JipJung/UI/Home/Main/File.swift
  JipJung/JipJung/UI/Home/Maxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteMaxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteSound/File.swift
  JipJung/JipJung/UI/Me/Main/File.swift
  JipJung/JipJung/UI/Sound/File.swift
Labels: 🔧conf

#21 🐛 동일 파일명에 의한 에러 해결
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Interfaces/File.swift
  JipJung/JipJung/Data/Repositories/File.swift
  JipJung/JipJung/Domain/Entities/File.swift
  JipJung/JipJung/Domain/Interfaces/File.swift
  JipJung/JipJung/Domain/UseCases/Protocol/File.swift
  JipJung/JipJung/Infra/File/File.swift
  JipJung/JipJung/Infra/LocalDB/File.swift
  JipJung/JipJung/Infra/Network/File.swift
  JipJung/JipJung/Infra/UserDefaults/File.swift
  JipJung/JipJung/UI/Common/Example.swift
  JipJung/JipJung/UI/Explore/Main/File.swift
  JipJung/JipJung/UI/Explore/Search/File.swift
  JipJung/JipJung/UI/Home/Categories/File.swift
  JipJung/JipJung/UI/Home/Focus/File.swift
  JipJung/JipJung/UI/Home/Main/File.swift
  JipJung/JipJung/UI/Home/Maxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteMaxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteSound/File.swift
  JipJung/JipJung/UI/Me/Main/File.swift
  JipJung/JipJung/UI/Sound/File.swift
Labels: 🐛 bug

#22 Revert "🐛 동일 파일명에 의한 에러 해결"
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Interfaces/File.swift
  JipJung/JipJung/Data/Repositories/File.swift
  JipJung/JipJung/Domain/Entities/File.swift
  JipJung/JipJung/Domain/Interfaces/File.swift
  JipJung/JipJung/Domain/UseCases/Protocol/File.swift
  JipJung/JipJung/Infra/File/File.swift
  JipJung/JipJung/Infra/LocalDB/File.swift
  JipJung/JipJung/Infra/Network/File.swift
  JipJung/JipJung/Infra/UserDefaults/File.swift
  JipJung/JipJung/UI/Common/Example.swift
  JipJung/JipJung/UI/Explore/Main/File.swift
  JipJung/JipJung/UI/Explore/Search/File.swift
  JipJung/JipJung/UI/Home/Categories/File.swift
  JipJung/JipJung/UI/Home/Focus/File.swift
  JipJung/JipJung/UI/Home/Main/File.swift
  JipJung/JipJung/UI/Home/Maxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteMaxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteSound/File.swift
  JipJung/JipJung/UI/Me/Main/File.swift
  JipJung/JipJung/UI/Sound/File.swift
Labels: 🚑️ 긴급

#23 Revert "🔧 프로젝트 폴더 구조 정의"
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/App/AppDelegate.swift
  JipJung/JipJung/App/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/App/Assets.xcassets/Contents.json
  JipJung/JipJung/App/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/App/SceneDelegate.swift
  JipJung/JipJung/AppDelegate.swift
  JipJung/JipJung/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/Assets.xcassets/Contents.json
  JipJung/JipJung/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/Data/Interfaces/File.swift
  JipJung/JipJung/Data/Repositories/File.swift
  JipJung/JipJung/Domain/Entities/File.swift
  JipJung/JipJung/Domain/Interfaces/File.swift
  JipJung/JipJung/Domain/UseCases/Protocol/File.swift
  JipJung/JipJung/Infra/File/File.swift
  JipJung/JipJung/Infra/LocalDB/File.swift
  JipJung/JipJung/Infra/Network/File.swift
  JipJung/JipJung/Infra/UserDefaults/File.swift
  JipJung/JipJung/SceneDelegate.swift
  JipJung/JipJung/UI/Common/Example.swift
  JipJung/JipJung/UI/Explore/Main/File.swift
  JipJung/JipJung/UI/Explore/Search/File.swift
  JipJung/JipJung/UI/Home/Categories/File.swift
  JipJung/JipJung/UI/Home/Focus/File.swift
  JipJung/JipJung/UI/Home/Main/File.swift
  JipJung/JipJung/UI/Home/Maxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteMaxim/File.swift
  JipJung/JipJung/UI/Me/FavoriteSound/File.swift
  JipJung/JipJung/UI/Me/Main/File.swift
  JipJung/JipJung/UI/Sound/File.swift
Labels: 🚑️ 긴급

#24 🔧 프로젝트 폴더 구조 재시도
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Interfaces/.gitkeep
  JipJung/JipJung/Data/Repositories/.gitkeep
  JipJung/JipJung/Domain/Entities/.gitkeep
  JipJung/JipJung/Domain/Interfaces/.gitkeep
  JipJung/JipJung/Domain/UseCases/Protocol/.gitkeep
  JipJung/JipJung/Infra/File/.gitkeep
  JipJung/JipJung/Infra/LocalDB/.gitkeep
  JipJung/JipJung/Infra/Network/.gitkeep
  JipJung/JipJung/Infra/UserDefaults/.gitkeep
  JipJung/JipJung/UI/Common/.gitkeep
  JipJung/JipJung/UI/Explore/Main/.gitkeep
  JipJung/JipJung/UI/Explore/Search/.gitkeep
  JipJung/JipJung/UI/Home/Categories/.gitkeep
  JipJung/JipJung/UI/Home/Focus/.gitkeep
  JipJung/JipJung/UI/Home/Main/.gitkeep
  JipJung/JipJung/UI/Home/Maxim/.gitkeep
  JipJung/JipJung/UI/Me/FavoriteMaxim/.gitkeep
  JipJung/JipJung/UI/Me/FavoriteSound/.gitkeep
  JipJung/JipJung/UI/Me/Main/.gitkeep
  JipJung/JipJung/UI/Sound/.gitkeep
Labels: 🐛 bug

#25 🔧 프로젝트 폴더 구조 정리
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/AppDelegate.swift
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/Application/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/Contents.json
  JipJung/JipJung/Application/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/Assets.xcassets/AccentColor.colorset/Contents.json
  JipJung/JipJung/Assets.xcassets/AppIcon.appiconset/Contents.json
  JipJung/JipJung/Assets.xcassets/Contents.json
  JipJung/JipJung/Base.lproj/LaunchScreen.storyboard
  JipJung/JipJung/Data/Interfaces/.gitkeep
  JipJung/JipJung/Data/Repositories/.gitkeep
  JipJung/JipJung/Domain/Entities/.gitkeep
  JipJung/JipJung/Domain/Interfaces/.gitkeep
  JipJung/JipJung/Domain/UseCases/Protocol/.gitkeep
  JipJung/JipJung/Infra/File/.gitkeep
  JipJung/JipJung/Infra/File/LocalFileManager.swift
  JipJung/JipJung/Infra/LocalDB/.gitkeep
  JipJung/JipJung/Infra/Network/.gitkeep
  JipJung/JipJung/Infra/UserDefaults/.gitkeep
  JipJung/JipJung/SceneDelegate.swift
  JipJung/JipJung/UI/Common/.gitkeep
  JipJung/JipJung/UI/Explore/Main/.gitkeep
  JipJung/JipJung/UI/Explore/Search/.gitkeep
  JipJung/JipJung/UI/Home/Categories/.gitkeep
  JipJung/JipJung/UI/Home/Focus/.gitkeep
  JipJung/JipJung/UI/Home/Main/.gitkeep
  JipJung/JipJung/UI/Home/Maxim/.gitkeep
  JipJung/JipJung/UI/Me/FavoriteMaxim/.gitkeep
  JipJung/JipJung/UI/Me/FavoriteSound/.gitkeep
  JipJung/JipJung/UI/Me/Main/.gitkeep
  JipJung/JipJung/UI/Sound/.gitkeep
Labels: 🔧conf

#36 탭바컨트롤러를 추가
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
  JipJung/JipJung/UI/Me/Main/MeViewController.swift
Labels: ✨ feature

#38 Entities 추가
  JipJung/.swiftlint.yml
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Domain/Entities/FavoriteMaxim.swift
  JipJung/JipJung/Domain/Entities/FavoriteMusic.swift
  JipJung/JipJung/Domain/Entities/Maxim.swift
  JipJung/JipJung/Domain/Entities/Music.swift
Labels: ✨ feature

#40 💄 UITabBar 디자인 변경
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/Localizing/Common.swift
Labels: ♻️ refactor, 🚑️ 긴급

#37 ✨UserDefaultsStorage 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Infra/UserDefaults/UserDefaultsStorage.swift
  JipJung/UserDefaultsStorageTest/UserDefaultsStorageTest.swift
Labels: ✨ feature

#41 Local File API 구현 및 Unit Test
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Infra/File/LocalFileManager.swift
  JipJung/LocalFileManagerTests/LocalFileManagerTests.swift
Labels: ✨ feature

#42 Realm 관련 구현
  .gitignore
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung.xcodeproj/xcshareddata/xcschemes/JipJung.xcscheme
  JipJung/JipJung/Domain/Entities/FavoriteMaxim.swift
  JipJung/JipJung/Domain/Entities/FavoriteMusic.swift
  JipJung/JipJung/Domain/Entities/Maxim.swift
  JipJung/JipJung/Domain/Entities/Music.swift
  JipJung/JipJung/Infra/LocalDB/RealmDBManager.swift
Labels: ✨ feature, 🔧conf

#44 📝 README 오류 수정
  README.md
Labels: 📝 docs

#46 ✨ Firebase API 구현
  .gitignore
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/Infra/Network/RemoteServiceProvider.swift
  JipJung/Podfile
  JipJung/Podfile.lock
Labels: ✨ feature

#45 ExploreViewController, SearchViewController 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/Localizing/Common.swift
  JipJung/JipJung/UI/Explore/Main/CollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/SearchViewController.swift
Labels: ✨ feature

#47 ✨ MusicCardCollectionViewCell 레이아웃 설정
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Common/MusicCardCollectionViewCell.swift
  JipJung/JipJung/UI/Common/UIView+Extension.swift
Labels: ✨ feature

#55 ✨ MediaRepository 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Infra/File/LocalFileManager.swift
  JipJung/JipJung/Infra/Network/MediaRepository.swift
  JipJung/JipJung/Infra/Network/RemoteServiceProvider.swift
Labels: ✨ feature

#54 RecentMusicViewController, FavoriteMusicViewController 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Common/MusicCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/CollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/SearchViewController.swift
  JipJung/JipJung/UI/Home/Main/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/RecentMusicViewController.swift
Labels: ✨ feature

#56 Explore 화면 MusicCollectionViewCell 연결, GenreCollectionViewCell 구현, 검색 히스토리 삭제 기능 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Localizing/Common.swift
  JipJung/JipJung/UI/Common/MusicCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/GenreCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/SearchViewController.swift
  JipJung/JipJung/UI/Home/Main/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/RecentMusicViewController.swift
Labels: ✨ feature

#59 🚑️ 프로젝트내에서 동일한 폴더가 보이는 문제 수정
  JipJung/JipJung.xcodeproj/project.pbxproj
Labels: 🚑️ 긴급

#58 ✨ 더미파일을 이용한 음원, 동영상 재생 구현
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
Labels: ✨ feature

#61 🐛identifier를 id로 변경
  JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
  JipJung/JipJung/UI/Home/Main/FavoriteMusicViewController.swift
Labels: 🚑️ 긴급

#62 ✨Infinity Focus 모드 UI 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Home/Main/InfinityFocusViewController.swift
Labels: ✨ feature

#66 이전 버전 InfinityFocusViewController가 업로드 된 문제 해결.
  JipJung/JipJung/UI/Home/Main/InfinityFocusViewController.swift
Labels: 🐛 bug, 🚑️ 긴급

#64 Home 음원 및 동영상 재생 배경 개선
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Domain/UseCases/AudioPlayUseCase.swift
  JipJung/JipJung/Domain/UseCases/MediaListUseCase.swift
  JipJung/JipJung/UI/Home/Main/Enums.swift
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/MediaCollectionViewCell.swift
  JipJung/JipJung/test2.mp4
Labels: ✨ feature

#70 집중시간 저장 기능과 관련한 유즈케이스, 엔터티, 레퍼지토리 구현 , Infinity 모드의 집중시간 저장 기능 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Common/Date+Extension.swift
  JipJung/JipJung/UI/Home/Main/FocusRecord.swift
  JipJung/JipJung/UI/Home/Main/FocusTimeRepository.swift
  JipJung/JipJung/UI/Home/Main/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Main/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/SaveFocusTimeUseCase.swift
Labels: ✨ feature

#71 💄 음원 상세 화면 틀 구현, 현재 화면 닫기 기능
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Dummy/sea.mp4
  JipJung/JipJung/UI/Me/Main/MeViewController.swift
  JipJung/JipJung/UI/Sound/CollectionView+MusicPlayerViewController.swift
  JipJung/JipJung/UI/Sound/MusicPlayerViewController.swift
  JipJung/JipJung/UI/Sound/Views/MusicDescriptionView.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerButtons.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerMaximView.swift
  JipJung/JipJung/UI/Sound/Views/TagCell.swift
Labels: ✨ feature

#69 DefaultFocusView Animation 구현하기
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Animation/CALayer+Extension.swift
  JipJung/JipJung/UI/Animation/CycleAnimation.swift
  JipJung/JipJung/UI/Animation/PulseAnimation.swift
  JipJung/JipJung/UI/Common/BlurCircleButton.swift
  JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/Enums.swift
  JipJung/JipJung/UI/Home/Focus/FocusViewControllerFactory.swift
  JipJung/JipJung/UI/Home/Focus/GenerateTimerUseCase.swift
  JipJung/JipJung/UI/Home/Focus/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/PomodoroFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
Labels: ✨ feature

#73 ✨ FocusViewController를 공통 부분을 묶고 Push, dismiss를 한번에 처리하도록 함
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/FocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/PomodoroFocusViewController.swift
  JipJung/JipJung/UI/Home/Home+Enums.swift
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
Labels: ✨ feature

#74 FocusView관련 미반영 이슈 반영
  JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/InfinityFocusViewController.swift
Labels: ✨ feature

#75 TimePickerView 배경색을 투명하게 변경
  JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
Labels: ✨ feature

#76 🐛 버그 수정 및 iOS 13 대응
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/UI/Common/MusicCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
Labels: 🐛 bug

#78 ✨ CometAnimation 구현하기
  JipJung/JipJung/UI/Home/Focus/InfinityFocusViewController.swift
Labels: ✨ feature

#83 Home/Main에 대한 리팩토링 - 중간 적용
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/Data/Interfaces/LocalDBManagable.swift
  JipJung/JipJung/Data/Interfaces/LocalFileAccessible.swift
  JipJung/JipJung/Data/Interfaces/RemoteServiceAccessible.swift
  JipJung/JipJung/Data/Repositories/MaximListRepository.swift
  JipJung/JipJung/Data/Repositories/MediaListRepository.swift
  JipJung/JipJung/Data/Repositories/MediaResourceRepository.swift
  JipJung/JipJung/Data/Repositories/RealmSettingRepository.swift
  JipJung/JipJung/Domain/Interfaces/MaximListRepositoryProtocol.swift
  JipJung/JipJung/Domain/Interfaces/MediaListRepositoryProtocol.swift
  JipJung/JipJung/Domain/Interfaces/MediaResourceRepositoryProtocol.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayUseCase.swift
  JipJung/JipJung/Domain/UseCases/BaseDataUseCase.swift
  JipJung/JipJung/Domain/UseCases/MaximListUseCase.swift
  JipJung/JipJung/Domain/UseCases/MediaListUseCase.swift
  JipJung/JipJung/Domain/UseCases/VideoPlayUseCase.swift
  JipJung/JipJung/Infra/File/LocalFileManager.swift
  JipJung/JipJung/Infra/LocalDB/RealmDBManager.swift
  JipJung/JipJung/Infra/Network/RemoteServiceProvider.swift
  JipJung/JipJung/Infra/UserDefaults/UserDefaultsStorage.swift
  JipJung/JipJung/UI/Common/Array+Extension.swift
  JipJung/JipJung/UI/Common/BlurEffect.swift
  JipJung/JipJung/UI/Common/SystemConstants.swift
  JipJung/JipJung/UI/Common/UIApplication+Extension.swift
  JipJung/JipJung/UI/Common/UIScreen+Extension.swift
  JipJung/JipJung/UI/Common/UIView+Extension.swift
  JipJung/JipJung/UI/Explore/Main/SearchViewController.swift
  JipJung/JipJung/UI/Home/Focus/FocusViewControllerFactory.swift
  JipJung/JipJung/UI/Home/Home+Enums.swift
  JipJung/JipJung/UI/Home/Main/FocusTimeRepository.swift
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/HomeViewModel.swift
Labels: ♻️ refactor

#85 FocusView의 presentation animation추가
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Animation/SlowPresent.swift
  JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/FocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Main/HomeViewController.swift
Labels: ✨ feature

#88 앱 초기화 부분 리팩토링, 번들 리소스 탑재를 위한 MediaResourceRepository 수정
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/Data/Repositories/MediaResourceRepository.swift
  JipJung/JipJung/Domain/UseCases/BaseDataUseCase.swift
  JipJung/JipJung/Infra/Bundle/BundleManager.swift
  JipJung/JipJung/Localizing/Common.swift
  JipJung/JipJung/UI/Home/Main/HomeViewModel.swift
  JipJung/JipJung/Utils/ApplicationLaunch.swift
  JipJung/JipJung/Utils/LocalDBMigrator.swift
  JipJung/JipJung/Utils/Utils+Enums.swift
Labels: ✨ feature, ♻️ refactor

#98 🎨 MVVM 형태에 맞도록 디렉토리 구조 수정
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Repositories/FocusTimeRepository.swift
  JipJung/JipJung/Domain/Entities/BrightMedia.swift
  JipJung/JipJung/Domain/Entities/FocusRecord.swift
  JipJung/JipJung/Domain/UseCases/SaveFocusTimeUseCase.swift
  JipJung/JipJung/UI/Common/Extensions/Array+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/Date+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/Int+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UIApplication+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UICollectionView+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UIScreen+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UITableView+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UIView+Extension.swift
  JipJung/JipJung/UI/Common/Views/BlurCircleButton.swift
  JipJung/JipJung/UI/Common/Views/FocusButton.swift
  JipJung/JipJung/UI/Common/Views/MusicCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/VIewModels/ExploreViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/GenreCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusViewControllerFactory.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/BreathFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/VIewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/MediaCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Main/Views/RecentMusicViewController.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximViewModel.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
  JipJung/JipJung/UI/Me/Main/ViewModels/MeViewModel.swift
  JipJung/JipJung/UI/Me/Main/Views/MeViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/CollectionView+MusicPlayerViewController.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: ♻️ refactor, 🚑️ 긴급

#101 Maxim화면 오토레이아웃 설정하기
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Common/Extensions/UILabel+Extension.swift
  JipJung/JipJung/UI/Common/Views/CloseButton.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
Labels: ✨ feature

#104 SearchViewController 리팩토링, 검색 기능 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Repositories/SearchHistoryRepository.swift
  JipJung/JipJung/Domain/UseCases/SearchHistoryUseCase.swift
  JipJung/JipJung/Domain/UseCases/SearchMediaUseCase.swift
  JipJung/JipJung/UI/Explore/Main/VIewModels/SearchViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
Labels: ✨ feature

#103 🐛 처음 재생 버튼을 누르면 음악 재생이 되지 않는 현상 수정
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Domain/UseCases/Audio+Enums.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayUseCase.swift
  JipJung/JipJung/UI/Home/Main/VIewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
Labels: 🐛 bug

#106 Home - 음악 재생: UIPageControl 및 UICollectionView의 Scroll 애니메이션, 무한 스크롤
  JipJung/JipJung/UI/Common/Extensions/UICollectionView+Extension.swift
  JipJung/JipJung/UI/Home/Main/VIewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/MediaCollectionViewCell.swift
Labels: ✨ feature

#107 Explore 태그 별 음원 목록 보여주는 기능, 음원 상세 화면 이동
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/Domain/UseCases/SearchMediaUseCase.swift
  JipJung/JipJung/Localizing/Common.swift
  JipJung/JipJung/UI/Common/Extensions/String+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UICollectionView+Extension.swift
  JipJung/JipJung/UI/Explore/Main/VIewModels/ExploreViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SoundTagCollectionViewCell.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: ✨ feature

#109 Bundle 연동, Home UI 개선
  .gitignore
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Repositories/MediaResourceRepository.swift
  JipJung/JipJung/Domain/Entities/Media.swift
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/Resource/.gitkeep
  JipJung/JipJung/UI/Common/Views/FocusButton.swift
  JipJung/JipJung/UI/Home/Main/VIewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/MediaCollectionViewCell.swift
Labels: ✨ feature

#113 ExploreViewModel 구현 및 바인딩 이외 추가작업
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Repositories/MyFavoriteRepository.swift
  JipJung/JipJung/Domain/Entities/Media.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
  JipJung/JipJung/Domain/UseCases/FavoriteMediaUseCase.swift
  JipJung/JipJung/Domain/UseCases/FetchMediaURLUseCase.swift
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/Infra/LocalDB/RealmDBManager.swift
  JipJung/JipJung/UI/Common/Views/MusicCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/VIewModels/ExploreViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/CollectionView+MusicPlayerViewController.swift
  JipJung/JipJung/UI/Sound/Views/MusicDescriptionView.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerButtons.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: ✨ feature

#111 Home - MaximViewModel 설계하기
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung.xcodeproj/xcshareddata/xcschemes/JipJung.xcscheme
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/Domain/Entities/DBStructureForJSON.swift
  JipJung/JipJung/Domain/Entities/Maxim.swift
  JipJung/JipJung/Domain/UseCases/MaximListUseCase.swift
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximViewModel.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
  JipJung/JipJung/Utils/ApplicationLaunch.swift
Labels: ✨ feature

#114 DummyData 갱신, 기본 Asset 갱신, 음원 배경색 설정 기능, 음원 이미지 설정 기능, 기타 UI 개선
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Domain/Entities/Media.swift
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/UI/Common/Extensions/UICollectionView+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UICollectionViewCell+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UIColor+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UITableView+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UITableViewCell+Extension.swift
  JipJung/JipJung/UI/Common/Views/MusicCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SoundTagCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Main/Views/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/RecentMusicViewController.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerMaximView.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
  JipJung/JipJung/UI/Sound/Views/TagCollectionViewCell.swift
Labels: ✨ feature, ♻️ refactor

#115 MaximCalendar 화면 제작하기
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/UI/Common/Extensions/Date+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UIView+Extension.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximViewModel.swift
  JipJung/JipJung/UI/Home/Maxim/Views/Maxim+Enums.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCalendarHeaderCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximHeaderCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
Labels: ✨ feature

#116 Focus - Breath 모드 애니메이션 구현, 기본 기능 구현
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Animation/BreathAnimation.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/BreathFocusViewModel.swift
Labels: ✨ feature

#118 ♻️ dequeResuableCell Extension 변경
  JipJung/JipJung/UI/Common/Extensions/UICollectionView+Extension.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/RecentMusicViewController.swift
Labels: ♻️ refactor

#121 🐛 Timer exit후 다시 실행되도록 수정, 타이머 시간 설정하기 기능 추가
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
  JipJung/JipJung/UI/Home/Home+Enums.swift
Labels: 🐛 bug

#124 🚑️ 아이폰 12에서 Breath모드 사용시 Crash나는 문제 수정, 네이밍 수정
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Animation/BreathAnimation.swift
  JipJung/JipJung/UI/Animation/WiggleAnimation.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusViewController.swift
Labels: 🚑️ 긴급

#127 타이머 종료 시 초기화 되지 않는 문제, 정지 버튼 클릭시 pause가 표시되지 않는 문제 해결
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
Labels: 🐛 bug, 🚑️ 긴급

#128 MaximImage 보여주기
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCalendarHeaderCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
Labels: ✨ feature

#133 🚀 앱 아이콘 추가
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/1024.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/114.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/120.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/180.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/29.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/40.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/57.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/58.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/60.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/80.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/87.png
  JipJung/JipJung/Application/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🔧conf

#129 타이머 시작/정지와 배경의 오디오 콘텐츠 재생/정지 연동
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Repositories/MediaResourceRepository.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayUseCase.swift
  JipJung/JipJung/Domain/UseCases/FetchMediaURLUseCase.swift
  JipJung/JipJung/Domain/UseCases/VideoPlayUseCase.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/VIewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/MediaCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Main/Views/MediaPlayView.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: ✨ feature

#136 🚀 앱 버전 갱신 및 화면 방향 고정
  JipJung/JipJung.xcodeproj/project.pbxproj
Labels: 🔧conf

#141 Feature/recent favorite
  JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
  JipJung/JipJung/UI/Common/Extensions/UIApplication+Extension.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Home/Home+Enums.swift
  JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: ✨ feature, 🐛 bug

#138 Feature/me
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/UI/Common/Extensions/UICollectionView+Extension.swift
  JipJung/JipJung/UI/Common/Extensions/UITableView+Extension.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Me/Main/Views/Me+Enums.swift
  JipJung/JipJung/UI/Me/Main/Views/MeDailyStaticsCollectionViewCell.swift
  JipJung/JipJung/UI/Me/Main/Views/MeExtraCollectionViewCell.swift
  JipJung/JipJung/UI/Me/Main/Views/MeHeaderCollectionReusableView.swift
  JipJung/JipJung/UI/Me/Main/Views/MeMonthYearStaticsCollectionViewCell.swift
  JipJung/JipJung/UI/Me/Main/Views/MeTableViewDailiyStaticsCell.swift
  JipJung/JipJung/UI/Me/Main/Views/MeViewController.swift
Labels: ✨ feature

#143 모드(Dark/Bright) 전환 기능 구현 (홈화면 제외)
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Infra/LocalDB/RealmDBManager.swift
  JipJung/JipJung/UI/Animation/ClubSKScene.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SoundTagCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Home+Enums.swift
  JipJung/JipJung/UI/Home/Main/VIewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
  JipJung/JipJung/Utils/ApplicationMode.swift
  JipJung/JipJung/Utils/Utils+Enums.swift
Labels: ✨ feature

#144 ✨ Focus - Breath 모드 기능 보완
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Animation/CountdownView.swift
  JipJung/JipJung/UI/Animation/WiggleAnimation.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/ViweModels/BreathFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/VIewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
Labels: ✨ feature

#146 잔디뷰 작성
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/Data/Repositories/FocusTimeRepository.swift
  JipJung/JipJung/Domain/Entities/DateFocusRecordDTO.swift
  JipJung/JipJung/Domain/Entities/FocusRecord.swift
  JipJung/JipJung/Domain/UseCases/LoadFocusTimeUseCase.swift
  JipJung/JipJung/Dummy/DummyFocusData.json
  JipJung/JipJung/Infra/LocalDB/RealmDBManager.swift
  JipJung/JipJung/UI/Common/Extensions/Date+Extension.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
  JipJung/JipJung/UI/Me/Main/ViewModels/MeViewModel.swift
  JipJung/JipJung/UI/Me/Main/Views/GrassMapView.swift
  JipJung/JipJung/UI/Me/Main/Views/GrassPresenterObject.swift
  JipJung/JipJung/UI/Me/Main/Views/Me+Enums.swift
  JipJung/JipJung/UI/Me/Main/Views/MeDailyStaticsCollectionViewCell.swift
  JipJung/JipJung/UI/Me/Main/Views/MeViewController.swift
  JipJung/JipJung/Utils/ApplicationLaunch.swift
Labels: ✨ feature

#148 기본 에셋/더미 데이터 갱신, 홈 화면 clubView 추가
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
Labels: ✨ feature

#149 ✨홈화면 다크모드 대응 완료
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
Labels: ✨ feature

#147 Feature/recent data
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Repositories/MediaListRepository.swift
  JipJung/JipJung/Data/Repositories/PlayHistoryRepository.swift
  JipJung/JipJung/Domain/Entities/PlayHistory.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayUseCase.swift
  JipJung/JipJung/Domain/UseCases/MediaListUseCase.swift
  JipJung/JipJung/Domain/UseCases/PlayHistoryUseCase.swift
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/Infra/LocalDB/RealmDBManager.swift
  JipJung/JipJung/UI/Common/Extensions/Array+Extension.swift
  JipJung/JipJung/UI/Explore/Main/ViewModels/ExploreViewModel.swift
  JipJung/JipJung/UI/Explore/Main/ViewModels/SearchViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/BreathFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
Labels: ✨ feature

#150 ✨Pomodoro 모드 완성
  JipJung/JipJung/UI/Home/Focus/ViewModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
Labels: ✨ feature

#151 ✨ 오늘 날짜부터 데이터를 보여주도록 변경
  JipJung/JipJung/Data/Repositories/MaximListRepository.swift
  JipJung/JipJung/Domain/UseCases/MaximListUseCase.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximViewModel.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCalendarHeaderCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
Labels: ✨ feature

#154 ✨ 집중모드 종료시 알림, 햅틱 피드백 추가
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
  JipJung/JipJung/Utils/ApplicationLaunch.swift
  JipJung/JipJung/Utils/FeedbackGenerator.swift
  JipJung/JipJung/Utils/PushNotificationManager.swift
Labels: ✨ feature

#156 모드 별 음원 리스트 저장/삭제 기능
  JipJung/JipJung/Data/Repositories/MediaListRepository.swift
  JipJung/JipJung/Domain/UseCases/MediaListUseCase.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MusicDescriptionView.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerButtons.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: ✨ feature

#155 Feature/Me 기능 완성
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/Dummy/DummyFocusData.json
  JipJung/JipJung/Localizing/Common.swift
  JipJung/JipJung/UI/Common/Extensions/UIColor+Extension.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCollectionViewCell.swift
  JipJung/JipJung/UI/Me/Main/ViewModels/MeViewModel.swift
  JipJung/JipJung/UI/Me/Main/Views/GrassMapView.swift
  JipJung/JipJung/UI/Me/Main/Views/GrassPresenterObject.swift
  JipJung/JipJung/UI/Me/Main/Views/Me+Enums.swift
  JipJung/JipJung/UI/Me/Main/Views/MeDailyStaticsView.swift
  JipJung/JipJung/UI/Me/Main/Views/MeViewController.swift
  JipJung/JipJung/Utils/ApplicationLaunch.swift
Labels: ✨ feature

#157 🐛 알림 메시지 오류 수정
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
  JipJung/JipJung/Utils/PushNotificationManager.swift
Labels: 🐛 bug

#159 🐛 실기기 및 시뮬레이터 버그 수정
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MusicDescriptionView.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
  JipJung/JipJung/Utils/ApplicationLaunch.swift
Labels: 🐛 bug

#182 음원상세화면 버그 해결
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: 🐛 bug

#181 Home: 음악 재생 관련 버그 수정
  JipJung/JipJung/UI/Common/Extensions/Notification+Extension.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusViewController.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
Labels: 🐛 bug

#183 🐛 indicator가 reuse될 때 pointer를 hidden을 하지않은 버그를 처리하기
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
Labels: 🐛 bug

#184 🐛 뽀모도로 화면에서 차오르는 게이지가 남은 시간에 맞게 수정, 타이머 최소 시간 단위 수정
  JipJung/JipJung/UI/Home/Focus/ViewModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
Labels: 🐛 bug, 👀Todo

#185 집중화면 모드 단말기 대응, 떠오르는 애니메이션 추가
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
Labels: 🐛 bug, ♻️ refactor

#187 ♻️ FocusViewController 구현체들의 코드 통일
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Common/Views/CloseButton.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/Focus+Enums.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
Labels: ♻️ refactor

#186 Refactoring/realm
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Data/Repositories/FavoriteRepository.swift
  JipJung/JipJung/Data/Repositories/FocusTimeRepository.swift
  JipJung/JipJung/Data/Repositories/MaximListRepository.swift
  JipJung/JipJung/Data/Repositories/MediaListRepository.swift
  JipJung/JipJung/Data/Repositories/MyFavoriteRepository.swift
  JipJung/JipJung/Data/Repositories/PlayHistoryRepository.swift
  JipJung/JipJung/Domain/Entities/BrightMedia.swift
  JipJung/JipJung/Domain/Entities/DarknessMedia.swift
  JipJung/JipJung/Domain/Entities/FavoriteMedia.swift
  JipJung/JipJung/Domain/Entities/PlayHistory.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
  JipJung/JipJung/Domain/UseCases/FavoriteMediaUseCase.swift
  JipJung/JipJung/Domain/UseCases/LoadFocusTimeUseCase.swift
  JipJung/JipJung/Domain/UseCases/MaximListUseCase.swift
  JipJung/JipJung/Domain/UseCases/MediaListUseCase.swift
  JipJung/JipJung/Domain/UseCases/PlayHistoryUseCase.swift
  JipJung/JipJung/Domain/UseCases/SaveFocusTimeUseCase.swift
  JipJung/JipJung/Domain/UseCases/SearchMediaUseCase.swift
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/Infra/LocalDB/LocalDBEnums.swift
  JipJung/JipJung/Infra/LocalDB/RealmDBManager.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/FavoriteViewModel.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/Utils/LocalDBMigrator.swift
Labels: ♻️ refactor

#189 MediaCell 가로 세로 비율 통일 및 Appearance 영향에 따른 이질적인 색상 조합 수정
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Common/Enums/Common+Enums.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Home/Home+Enums.swift
  JipJung/JipJung/UI/Home/Main/Views/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/PlayHistoryViewController.swift
Labels: 🐛 bug, ♻️ refactor

#194 홈 화면의 focus 모드 버튼 이미지 추가
  JipJung/JipJung/Application/Assets.xcassets/focus_breath.imageset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/focus_breath.imageset/focus_breath.png
  JipJung/JipJung/Application/Assets.xcassets/focus_default.imageset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/focus_default.imageset/focus_default.png
  JipJung/JipJung/Application/Assets.xcassets/focus_infinite.imageset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/focus_infinite.imageset/focus_infinite.png
  JipJung/JipJung/Application/Assets.xcassets/focus_pomodoro.imageset/Contents.json
  JipJung/JipJung/Application/Assets.xcassets/focus_pomodoro.imageset/focus_pomodoro.png
  JipJung/JipJung/UI/Common/Views/FocusButton.swift
  JipJung/JipJung/UI/Home/Home+Enums.swift
Labels: ✨ feature
