Repository boostcampwm-2021/iOS10-JipJung, pull requests merged in 2021-12, with the labels that each got.

#196 Audio 관련 코드 전반적인 개선작업 수행
  JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
  JipJung/JipJung/Domain/UseCases/AudioPlayUseCase.swift
  JipJung/JipJung/Domain/UseCases/PlayHistoryUseCase.swift
  JipJung/JipJung/UI/Common/Extensions/Notification+Extension.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/BreathFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: 🐛 bug, ♻️ refactor

#197 MaximListUseCase Test코드 추가 & 테스트환경 구축
  JipJung/.swiftlint.yml
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung.xcodeproj/xcshareddata/xcschemes/JipJung.xcscheme
  JipJung/JipJung/Data/Repositories/MaximListRepository.swift
  JipJung/JipJung/Domain/Entities/FocusRecord.swift
  JipJung/JipJung/Domain/UseCases/MaximListUseCase.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximViewModel.swift
  JipJung/MaximTests/MaximListRepositoryStub.swift
  JipJung/MaximTests/MaximListUseCaseTests.swift
  JipJung/MeTests/MeTests.swift
  JipJung/Podfile
  JipJung/Podfile.lock
Labels: ♻️ refactor, 🔧conf

#198 focus 화면들 리팩토링
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Home/Focus/ViewModels/BreathFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusButtons.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
Labels: ♻️ refactor

#199 Explore 화면 버그 수정 및 리팩토링
  JipJung/JipJung/Dummy/DummyData.json
  JipJung/JipJung/UI/Explore/Main/ViewModels/ExploreViewModel.swift
  JipJung/JipJung/UI/Explore/Main/ViewModels/SearchViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Sound/Views/MusicDescriptionView.swift
  JipJung/JipJung/UI/Sound/Views/TagCollectionViewCell.swift
Labels: 🐛 bug, ♻️ refactor

#200 🐛 아이폰 12 mini등에서 명언 설명이 짤리는 버그 해결
  JipJung/JipJung/UI/Sound/Views/MusicPlayerMaximView.swift
Labels: ✨ feature

#201 🎨 코드 스타일 통일 작업 - 진행 중
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Domain/Entities/FavoriteMaxim.swift
  JipJung/JipJung/Domain/Managers/Audio+Enums.swift
  JipJung/JipJung/Domain/Managers/AudioPlayManager.swift
  JipJung/JipJung/Domain/UseCases/LoadFocusTimeUseCase.swift
  JipJung/JipJung/UI/Common/Extensions/String+Extension.swift
  JipJung/JipJung/UI/Explore/Main/ViewModels/ExploreViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Home/Focus/Focus+Enums.swift
  JipJung/JipJung/UI/Home/Maxim/Maxim+Enums.swift
  JipJung/JipJung/UI/Me/Me+Enums.swift
  JipJung/JipJung/UI/Sound/ViewModels/MusicPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MusicDescriptionView.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerViewController.swift
Labels: ♻️ refactor

#203 Explore 탭 화면 코드스타일 통일성있게 변경
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Common/Views/MediaCollectionViewCell.swift
  JipJung/JipJung/UI/Explore/Main/ViewModels/ExploreViewModel.swift
  JipJung/JipJung/UI/Explore/Main/ViewModels/SearchViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/ExploreViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchTableViewCell.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Explore/Main/Views/SoundTagCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Main/Views/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/PlayHistoryViewController.swift
  JipJung/JipJung/UI/Sound/ViewModels/MediaPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MediaDescriptionView.swift
  JipJung/JipJung/UI/Sound/Views/MediaPlayerMaximView.swift
  JipJung/JipJung/UI/Sound/Views/MediaPlayerViewController.swift
  JipJung/JipJung/UI/Sound/Views/MusicPlayerButtons.swift
  JipJung/JipJung/UI/Sound/Views/TagCollectionViewCell.swift
Labels: ♻️ refactor

#204 Home/Main 코드스타일 통일성있게 변경
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/Application/AppDelegate.swift
  JipJung/JipJung/Application/SceneDelegate.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/HomeViewModel.swift
  JipJung/JipJung/UI/Home/Main/ViewModels/PlayHistoryViewModel.swift
  JipJung/JipJung/UI/Home/Main/Views/BlurCircleButton.swift
  JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
  JipJung/JipJung/UI/Home/Main/Views/FavoriteMusicViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/FocusButton.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeListHeaderView.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/PlayHistoryViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/TouchTransferView.swift
  JipJung/JipJung/Utils/ApplicationLaunch.swift
  JipJung/JipJung/Utils/ApplicationMode.swift
  JipJung/JipJung/Utils/FeedbackGenerator.swift
  JipJung/JipJung/Utils/PushNotificationManager.swift
Labels: ♻️ refactor

#205 Me & Maxim 코드 컨벤션 통일하기
  JipJung/JipJung.xcodeproj/project.pbxproj
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCalendarHeaderCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximCollectionViewCell.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
  JipJung/JipJung/UI/Me/Main/Views/GrassPresenterObject.swift
  JipJung/JipJung/UI/Me/Main/Views/MeDailyStaticsView.swift
  JipJung/JipJung/UI/Me/Main/Views/MeExtraCollectionViewCell.swift
  JipJung/JipJung/UI/Me/Main/Views/MeHeaderCollectionReusableView.swift
  JipJung/JipJung/UI/Me/Main/Views/MeMonthYearStaticsCollectionViewCell.swift
  JipJung/JipJung/UI/Me/Main/Views/MeViewController.swift
Labels: ♻️ refactor

#206 focus, animation 쪽 코드 스타일 통일
  JipJung/.swiftlint.yml
  JipJung/JipJung/UI/Animation/CALayer+Extension.swift
  JipJung/JipJung/UI/Animation/ClubSKScene.swift
  JipJung/JipJung/UI/Animation/CountdownView.swift
  JipJung/JipJung/UI/Animation/CycleAnimation.swift
  JipJung/JipJung/UI/Animation/PulseAnimation.swift
  JipJung/JipJung/UI/Animation/SlowPresent.swift
  JipJung/JipJung/UI/Animation/WiggleAnimation.swift
  JipJung/JipJung/UI/Home/Focus/Focus+Enums.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/BreathFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/DefaultFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/InfinityFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/ViewModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/FocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/PomodoroFocusViewController.swift
Labels: ♻️ refactor

#214 Default, 뽀모도로 모드에서 음원재생이 안되고 Default에서 continue시 화면 갱신되지 않은 문제 수정
  JipJung/JipJung/UI/Home/Focus/ViewModels/PomodoroFocusViewModel.swift
  JipJung/JipJung/UI/Home/Focus/Views/DefaultFocusViewController.swift
Labels: 🐛 bug

#215 🐛검색 히스토리 삭제관련 버그 해결
  JipJung/JipJung/UI/Explore/Main/ViewModels/SearchViewModel.swift
  JipJung/JipJung/UI/Explore/Main/Views/SearchViewController.swift
  JipJung/JipJung/UI/Home/Main/Views/HomeViewController.swift
Labels: 🐛 bug

#216 🐛 손쉬운 사용 폰트 크기가 미치는 영향을 고려하기
  JipJung/JipJung/UI/Me/Main/Views/MeDailyStaticsView.swift
  JipJung/JipJung/UI/Me/Main/Views/MeViewController.swift
Labels: ✨ feature

#217 ♻️ 음원 다운로드 후 자동 재생이 안되도록 변경
  JipJung/JipJung/UI/Sound/ViewModels/MediaPlayerViewModel.swift
  JipJung/JipJung/UI/Sound/Views/MediaPlayerViewController.swift
Labels: ♻️ refactor

#218 🐛 Commet 버그 해결
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
Labels: 🐛 bug

#221 ♻️ Comet 애니메이션 버그해결하기
  JipJung/JipJung/UI/Home/Focus/Views/BreathFocusViewController.swift
  JipJung/JipJung/UI/Home/Focus/Views/InfinityFocusViewController.swift
Labels: ♻️ refactor

#223 맥심화면 버그 해결
  JipJung/JipJung/UI/Home/Maxim/Maxim+Enums.swift
  JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximViewModel.swift
  JipJung/JipJung/UI/Home/Maxim/Views/MaximViewController.swift
Labels: 🐛 bug
